version: '3.9'

services:
  database:
    image: oc-9-database:latest
    container_name: database
    restart: always
    networks:
      - medilab-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_USER=postgres

  backend:
    build:
      context: ../
      dockerfile: docker/Backend.Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - database
    networks:
      - medilab-network
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/medilab
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rootroot

  gateway:
    build:
      context: ../
      dockerfile: docker/Gateway.Dockerfile
    container_name: gateway
    restart: always
    depends_on:
      - backend
    networks:
      - medilab-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://backend:8081
      - SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0=Path=/patients/**

networks:
  medilab-network:
    driver: bridge