version: '3.9'

services:
  database:
    image: oc-9-database:latest
    container_name: database-test
    restart: always
    ports:
      - "5432:5432"
    networks:
      - medilab-network-test
    environment:
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_USER=postgres
    volumes:
      - ./database/initialize-testing.sql:/docker-entrypoint-initdb.d/initialize-testing.sql
  
  backend:
    build:
      context: ../
      dockerfile: docker/Backend.Dockerfile
    container_name: backend-test
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - medilab-network-test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-test:5432/medilab
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rootroot

networks:
  medilab-network-test:
    driver: bridge