spring:
  cloud:
    gateway:
      routes:
        - id: backend-service
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: false
            maxAge: 3600

  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"