spring:
  cloud:
    gateway:
      routes:
        - id: backend-service
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**

  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"