spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/medilab
    username: postgres
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    fr.swynn: "debug"