spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/medilab
    username: postgres
    password: rootroot
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    fr:
      swynn: INFO